### ISSUE TITLE
Email and Twitter Cogs

### ISSUE THREAD

**Issue by EasilyTom** [RohanJagpal/SimonLett#2]
run.py alludes to existence of twitter.py and emails.py but these are not included in repo.

**Comment by Soggy-Crumpet** [comment]
The cogs haven't been created yet, so I commented it out of the initial extensions

**Comment by Soggy-Crumpet** [comment]
@Furri777 cogs have been created with intended functionality described in the relevant files. Feel free to begin work, just let me know what you're doing if you do decide to make a start.

**Comment by Soggy-Crumpet** [comment]
@Furri777 Get notified.

**Comment by EasilyTom** [comment]
@RohanJagpal OK.
